name: tax_project_new
version: "1.0.0"

profile: tax_project_new

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tax_project_new:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table